### ISSUE TITLE
Cant calculate threat with some character

### ISSUE THREAD

**Issue by JanedoeGVA** [jvd33/ClassicThreat#28] opened 2020-02-10 15:13 UTC
I have tried to use Warrior Threat Estimator with a Classic Warcraft Logs , it works with some tanks but when i tried with "Janedöe" it wasnt working for this log :https://classic.warcraftlogs.com/reports/MWALNphvZ8jP7HXJ
Same for druid with this one "Norrinradd" for this log :
https://classic.warcraftlogs.com/reports/MWALNphvZ8jP7HXJ

![image](https://user-images.githubusercontent.com/36301580/74161978-329c7400-4c20-11ea-8fea-cb31e51893b9.png)

**Comment by jvd33** [comment] 2020-02-10 16:02
Thanks for bringing this to my attention!

I know the cause and will work on getting a solution in quickly...Just last night there were issues with the `translate` query string param sent to Warcraft Logs when requesting the fights in the log that caused the reports to return with no valid fights, so I removed the translate query string and it had the side effect of borking non-english logs.

Going to experiment with just re-adding the translate parameter, since having functioning non-english logs is more important to me than a few edge case logs that fail to process. Long term I'll probably look into localization, but that's a whole different beast.

I'll let you know when I have a fix in!

**Comment by JanedoeGVA** [comment] 2020-02-10 17:33
Thank you for your work !
Damm fucking french :D I dont understand why the warcraft log is not in english...

**Comment by jvd33** [comment] 2020-02-10 22:22
I've believe I've tracked down the issue and fixed it, should be all set now.

Tentatively closing this, but feel free to reopen it (or make more) if you run into any more issues!

**Closed by jvd33** 2020-02-10 22:22 UTC

**Comment by JanedoeGVA** [comment] 2020-02-11 08:50
Thank you, it works. Really fast ! Good job :)
